/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InstallRouteImport } from './routes/install'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthDesktopStartRouteImport } from './routes/api/auth/desktop-start'
import { Route as ApiAuthDesktopRefreshRouteImport } from './routes/api/auth/desktop-refresh'
import { Route as ApiAuthDesktopExchangeRouteImport } from './routes/api/auth/desktop-exchange'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedChatProjectIdRouteImport } from './routes/_authenticated/chat.$projectId'

const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDesktopStartRoute = ApiAuthDesktopStartRouteImport.update({
  id: '/api/auth/desktop-start',
  path: '/api/auth/desktop-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDesktopRefreshRoute = ApiAuthDesktopRefreshRouteImport.update({
  id: '/api/auth/desktop-refresh',
  path: '/api/auth/desktop-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDesktopExchangeRoute = ApiAuthDesktopExchangeRouteImport.update({
  id: '/api/auth/desktop-exchange',
  path: '/api/auth/desktop-exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatProjectIdRoute =
  AuthenticatedChatProjectIdRouteImport.update({
    id: '/chat/$projectId',
    path: '/chat/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/chat/$projectId': typeof AuthenticatedChatProjectIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/desktop-exchange': typeof ApiAuthDesktopExchangeRoute
  '/api/auth/desktop-refresh': typeof ApiAuthDesktopRefreshRoute
  '/api/auth/desktop-start': typeof ApiAuthDesktopStartRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/chat/$projectId': typeof AuthenticatedChatProjectIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/desktop-exchange': typeof ApiAuthDesktopExchangeRoute
  '/api/auth/desktop-refresh': typeof ApiAuthDesktopRefreshRoute
  '/api/auth/desktop-start': typeof ApiAuthDesktopStartRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/install': typeof InstallRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/_authenticated/chat/$projectId': typeof AuthenticatedChatProjectIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/desktop-exchange': typeof ApiAuthDesktopExchangeRoute
  '/api/auth/desktop-refresh': typeof ApiAuthDesktopRefreshRoute
  '/api/auth/desktop-start': typeof ApiAuthDesktopStartRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/install'
    | '/dashboard'
    | '/api/uploadthing'
    | '/chat/$projectId'
    | '/api/auth/callback'
    | '/api/auth/desktop-exchange'
    | '/api/auth/desktop-refresh'
    | '/api/auth/desktop-start'
    | '/api/auth/sign-in'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/install'
    | '/dashboard'
    | '/api/uploadthing'
    | '/chat/$projectId'
    | '/api/auth/callback'
    | '/api/auth/desktop-exchange'
    | '/api/auth/desktop-refresh'
    | '/api/auth/desktop-start'
    | '/api/auth/sign-in'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/install'
    | '/_authenticated/dashboard'
    | '/api/uploadthing'
    | '/_authenticated/chat/$projectId'
    | '/api/auth/callback'
    | '/api/auth/desktop-exchange'
    | '/api/auth/desktop-refresh'
    | '/api/auth/desktop-start'
    | '/api/auth/sign-in'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  InstallRoute: typeof InstallRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthDesktopExchangeRoute: typeof ApiAuthDesktopExchangeRoute
  ApiAuthDesktopRefreshRoute: typeof ApiAuthDesktopRefreshRoute
  ApiAuthDesktopStartRoute: typeof ApiAuthDesktopStartRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/desktop-start': {
      id: '/api/auth/desktop-start'
      path: '/api/auth/desktop-start'
      fullPath: '/api/auth/desktop-start'
      preLoaderRoute: typeof ApiAuthDesktopStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/desktop-refresh': {
      id: '/api/auth/desktop-refresh'
      path: '/api/auth/desktop-refresh'
      fullPath: '/api/auth/desktop-refresh'
      preLoaderRoute: typeof ApiAuthDesktopRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/desktop-exchange': {
      id: '/api/auth/desktop-exchange'
      path: '/api/auth/desktop-exchange'
      fullPath: '/api/auth/desktop-exchange'
      preLoaderRoute: typeof ApiAuthDesktopExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$projectId': {
      id: '/_authenticated/chat/$projectId'
      path: '/chat/$projectId'
      fullPath: '/chat/$projectId'
      preLoaderRoute: typeof AuthenticatedChatProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedChatProjectIdRoute: typeof AuthenticatedChatProjectIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedChatProjectIdRoute: AuthenticatedChatProjectIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  InstallRoute: InstallRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthDesktopExchangeRoute: ApiAuthDesktopExchangeRoute,
  ApiAuthDesktopRefreshRoute: ApiAuthDesktopRefreshRoute,
  ApiAuthDesktopStartRoute: ApiAuthDesktopStartRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
